@startuml

actor Client
participant "Load Balancer / ECS" as LoadBalancer
participant RemoveBookFromCatalogActivity
participant CatalogDao
database DynamoDB

Client -> LoadBalancer: HTTP request
LoadBalancer -> RemoveBookFromCatalogActivity: execute(RemoveBookRequest)
RemoveBookFromCatalogActivity -> CatalogDao: removeBookFromCatalog(bookId)
CatalogDao -> DynamoDB: query for latest version of (bookId)

alt if bookId does not exist or book is not active
RemoveBookFromCatalogActivity <- CatalogDao: throw BookNotFoundException
LoadBalancer <- RemoveBookFromCatalogActivity: transform to KindlePublishingClientException
Client <- LoadBalancer: 400 Response
end

CatalogDao -> DynamoDB: update inactive:true
CatalogDao <- DynamoDB: return updated CatalogItemVersion
RemoveBookFromCatalogActivity <- CatalogDao: RemoveBookFromCatalogResponse
LoadBalancer <- RemoveBookFromCatalogActivity: RemoveBookFromCatalogResponse
Client <- LoadBalancer: 200 response

@enduml